import * as fs from 'fs';
import * as path from 'path';
import { trace, readFileLines, extractCodeRegion } from '@why-is-this/core';
import { loadConfig, getGitHubToken } from '../config';
import { parseFileArg } from './query';

export async function runAdr(target: string, opts: { output?: string }): Promise<void> {
  const { file, start, end } = parseFileArg(target);
  const config = loadConfig();
  const token = getGitHubToken(config);

  const record = await trace(file, start, end, { githubToken: token });
  const lines = readFileLines(process.cwd(), file);
  const codeLines = extractCodeRegion(lines, start, end);
  const date = new Date().toISOString().slice(0, 10);

  const title = record.rationale?.summary ?? `Decision: ${file}:${start}-${end}`;

  const chainSection = record.chain
    .slice(0, 5)
    .map(l => `- [${l.type}](${l.url}) (confidence: ${l.confidence.toFixed(2)}) — ${l.excerpt}`)
    .join('\n');

  const constraintsSection = record.rationale?.constraintsAtTime
    .map(c => `- \`${c.tag}\` ${c.description}`)
    .join('\n') ?? '_No constraints recorded._';

  const altsSection = record.rationale?.alternativesConsidered
    .map(a => `- ${a}`)
    .join('\n') ?? '_No alternatives recorded._';

  const adr = `# ADR: ${title}

Date: ${date}
Status: Accepted
Code region: \`${file}:${start}${end !== start ? '-' + end : ''}\`

## Context

${record.rationale?.detail ?? '_No rationale recorded. Run `why-is-this annotate` to add one._'}

## Decision

\`\`\`
${codeLines.join('\n')}
\`\`\`

## Rationale

Assembled from decision chain (fear score: ${record.fearScore.toFixed(2)}, bus factor: ${record.busFactorScore}):

${chainSection || '_No chain links found._'}

## Alternatives Considered

${altsSection}

## Constraints at Time of Decision

${constraintsSection}

## Consequences

_Fill in: what are the expected positive and negative consequences of this decision?_

---
_Generated by why-is-this on ${date}_
`;

  if (opts.output) {
    fs.mkdirSync(path.dirname(opts.output), { recursive: true });
    fs.writeFileSync(opts.output, adr, 'utf-8');
    console.log(`ADR written to ${opts.output}`);
  } else {
    process.stdout.write(adr);
  }
}
