import { listRationaleFiles } from '@why-is-this/core';
import { writeOutput } from '../util';

export async function runOnboard(targetPath: string, opts: { for?: string; output?: string }): Promise<void> {
  const repoPath = process.cwd();
  const roleDescription = opts.for ?? 'new team member';

  const rationaleFiles = listRationaleFiles(repoPath);
  const prefix = targetPath.replace(/^\.\//, '').replace(/\\/g, '/');
  const relevant = rationaleFiles
    .filter(r => r.target.file.replace(/\\/g, '/').startsWith(prefix))
    .sort((a, b) => (b.rationale.stillValid === false ? 1 : 0) - (a.rationale.stillValid === false ? 1 : 0));

  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push(`# Onboarding Guide: ${targetPath}`);
  lines.push(`> Generated by why-is-this on ${date} for: **${roleDescription}**\n`);
  lines.push(`## Overview\n`);
  lines.push(`This guide introduces the most consequential code in \`${targetPath}\`, ordered by risk and decision complexity.\n`);

  if (relevant.length === 0) {
    lines.push(`> No rationale annotations found in \`${targetPath}\`. Run \`why-is-this annotate\` to start building the knowledge layer.\n`);
  }

  for (let i = 0; i < relevant.length; i++) {
    const r = relevant[i];
    lines.push(`## ${i + 1}. ${r.rationale.summary}`);
    lines.push(`**File:** \`${r.target.file}:${r.target.lineRange[0]}-${r.target.lineRange[1]}\``);
    lines.push('');
    lines.push(r.rationale.detail);
    lines.push('');
    if (r.rationale.alternativesConsidered.length > 0) {
      lines.push(`**Alternatives considered:**`);
      for (const alt of r.rationale.alternativesConsidered) lines.push(`- ${alt}`);
      lines.push('');
    }
    if (r.rationale.constraintsAtTime.length > 0) {
      lines.push(`**Constraints at time of decision:**`);
      for (const c of r.rationale.constraintsAtTime) {
        lines.push(`- \`${c.tag}\` ${c.description}${c.survivorshipCheck ? ' _(survivorship check enabled)_' : ''}`);
      }
      lines.push('');
    }
    if (r.rationale.stillValid === false) {
      lines.push(`> ⚠️ **Survivorship flag:** One or more constraints may no longer apply. Review before modifying.`);
      lines.push('');
    }
    lines.push(`**Tags:** ${r.rationale.tags.join(', ') || '_none_'}`);
    lines.push(`**Author:** @${r.rationale.authorGitHub} (annotated ${r.rationale.createdAt.slice(0, 10)})`);
    lines.push('---\n');
  }

  lines.push(`## Safe to Change\n`);
  lines.push(`Files and regions NOT listed above have no rationale records — verify with git history before modifying.\n`);

  const output = lines.join('\n');
  if (opts.output) {
    writeOutput(opts.output, output);
    console.log(`Onboarding guide written to ${opts.output}`);
  } else {
    process.stdout.write(output);
  }
}
